/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Credentials;
using Sdkgen.Client.Exception;

namespace SdkFabric.Twitter;

public class Client : ClientAbstract
{
    public Client(string baseUrl, ICredentials credentials) : base(baseUrl, credentials)
    {
    }

    public TweetTag Tweet()
    {
        return new TweetTag(
            this.HttpClient,
            this.Parser
        );
    }

    public UsageTag Usage()
    {
        return new UsageTag(
            this.HttpClient,
            this.Parser
        );
    }

    public UserTag User()
    {
        return new UserTag(
            this.HttpClient,
            this.Parser
        );
    }

    public BookmarkTag Bookmark()
    {
        return new BookmarkTag(
            this.HttpClient,
            this.Parser
        );
    }

    public SearchTag Search()
    {
        return new SearchTag(
            this.HttpClient,
            this.Parser
        );
    }

    public QuoteTag Quote()
    {
        return new QuoteTag(
            this.HttpClient,
            this.Parser
        );
    }

    public TrendsTag Trends()
    {
        return new TrendsTag(
            this.HttpClient,
            this.Parser
        );
    }

    public RetweetTag Retweet()
    {
        return new RetweetTag(
            this.HttpClient,
            this.Parser
        );
    }



    public static Client Build(string token)
    {
        return new Client("https://api.twitter.com", new HttpBearer(token));
    }
}
