/**
 * Errors automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Twitter;

public class Errors
{
    [JsonPropertyName("errors")]
    public System.Collections.Generic.List<Error>? Errors { get; set; }

}

