/**
 * ErrorsException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using Sdkgen.Client.Exception;

namespace SdkFabric.Twitter;

public class ErrorsException : KnownStatusCodeException
{
    public Errors Payload;

    public ErrorsException(Errors payload)
    {
        this.Payload = payload;
    }
}
