/**
 * HideReplyResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Twitter;

public class HideReplyResponse
{
    [JsonPropertyName("data")]
    public HideReply? Data { get; set; }

}

