/**
 * LikeResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Twitter;
public class LikeResponse
{
    [JsonPropertyName("data")]
    public LikeResponseMessage? Data { get; set; }
}
