/**
 * SearchTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace SdkFabric.Twitter;

public class SearchTag : TagAbstract {
    public SearchTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    public async Task<TweetCollection> GetRecent(string query, string startTime, string endTime, string sinceId, string untilId, string sortOrder, string expansions, int maxResults, Fields fields)
    {
        Dictionary<string, object> pathParams = new();

        Dictionary<string, object> queryParams = new();
        queryParams.Add("query", query);
        queryParams.Add("start_time", startTime);
        queryParams.Add("end_time", endTime);
        queryParams.Add("since_id", sinceId);
        queryParams.Add("until_id", untilId);
        queryParams.Add("sort_order", sortOrder);
        queryParams.Add("expansions", expansions);
        queryParams.Add("max_results", maxResults);
        queryParams.Add("fields", fields);

        List<string> queryStructNames = new();
        queryStructNames.Add('fields'),

        RestRequest request = new(this.Parser.Url("/2/tweets/search/recent", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<TweetCollection>(response.Content);
        }

        if (response.ErrorException != null)
        {
            throw new ClientException("An unknown error occurred: " + response.ErrorException.Message, response.ErrorException);
        }

        throw (int) response.StatusCode switch
        {
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }


}
