/**
 * SingleTweet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Twitter;
public class SingleTweet
{
    [JsonPropertyName("tweet_id")]
    public string? TweetId { get; set; }
}
