/**
 * TrendCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Twitter;
public class TrendCollection
{
    [JsonPropertyName("data")]
    public System.Collections.Generic.List<Trend>? Data { get; set; }
}
