/**
 * TweetUsage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Twitter;
public class TweetUsage
{
    [JsonPropertyName("cap_reset_day")]
    public int? CapResetDay { get; set; }
    [JsonPropertyName("project_cap")]
    public string? ProjectCap { get; set; }
    [JsonPropertyName("project_id")]
    public string? ProjectId { get; set; }
    [JsonPropertyName("project_usage")]
    public string? ProjectUsage { get; set; }
}
