/**
 * TweetEntityResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Twitter;
public class TweetEntityResponse
{
    [JsonPropertyName("data")]
    public TweetDetails? Data { get; set; }
}
