/**
 * TweetCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Twitter;
public class TweetCollection
{
    [JsonPropertyName("data")]
    public List<TweetDetails>? Data { get; set; }
}
