/**
 * UserTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace SdkFabric.Twitter;

public class UserTag : TagAbstract {
    public UserTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    /**
     * Allows you to retrieve a collection of the most recent Tweets and Retweets posted by you and users you follow. This endpoint can return every Tweet created on a timeline over the last 7 days as well as the most recent 800 regardless of creation date.
     */
    public async Task<TweetCollection> GetTimeline(string userId, string exclude, string expansions, Pagination pagination, Fields fields)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("user_id", userId);

        Dictionary<string, object> queryParams = new();
        queryParams.Add("exclude", exclude);
        queryParams.Add("expansions", expansions);
        queryParams.Add("pagination", pagination);
        queryParams.Add("fields", fields);

        List<string> queryStructNames = new();
        queryStructNames.Add('pagination');
        queryStructNames.Add('fields');

        RestRequest request = new(this.Parser.Url("/2/users/:user_id/timelines/reverse_chronological", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<TweetCollection>(response.Content);
        }

        if (response.ErrorException != null)
        {
            throw new ClientException("An unknown error occurred: " + response.ErrorException.Message, response.ErrorException);
        }

        throw (int) response.StatusCode switch
        {
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }

    /**
     * Tweets liked by a user
     */
    public async Task<TweetCollection> GetLikedTweets(string userId, string expansions, int maxResults, string paginationToken, Fields fields)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("user_id", userId);

        Dictionary<string, object> queryParams = new();
        queryParams.Add("expansions", expansions);
        queryParams.Add("max_results", maxResults);
        queryParams.Add("pagination_token", paginationToken);
        queryParams.Add("fields", fields);

        List<string> queryStructNames = new();
        queryStructNames.Add('fields');

        RestRequest request = new(this.Parser.Url("/2/users/:user_id/liked_tweets", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<TweetCollection>(response.Content);
        }

        if (response.ErrorException != null)
        {
            throw new ClientException("An unknown error occurred: " + response.ErrorException.Message, response.ErrorException);
        }

        throw (int) response.StatusCode switch
        {
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }

    /**
     * Allows a user or authenticated user ID to unlike a Tweet.
     */
    public async Task<LikeResponse> RemoveLike(string userId, string tweetId)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("user_id", userId);
        pathParams.Add("tweet_id", tweetId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/2/users/:user_id/likes/:tweet_id", pathParams), Method.Delete);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<LikeResponse>(response.Content);
        }

        if (response.ErrorException != null)
        {
            throw new ClientException("An unknown error occurred: " + response.ErrorException.Message, response.ErrorException);
        }

        throw (int) response.StatusCode switch
        {
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }

    /**
     * Causes the user ID identified in the path parameter to Like the target Tweet.
     */
    public async Task<LikeResponse> CreateLike(string userId, SingleTweet payload)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("user_id", userId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/2/users/:user_id/likes", pathParams), Method.Post);
        this.Parser.Query(request, queryParams, queryStructNames);
        request.AddJsonBody(JsonSerializer.Serialize(payload));

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<LikeResponse>(response.Content);
        }

        if (response.ErrorException != null)
        {
            throw new ClientException("An unknown error occurred: " + response.ErrorException.Message, response.ErrorException);
        }

        throw (int) response.StatusCode switch
        {
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }

    /**
     * Returns a variety of information about one or more users specified by their usernames.
     */
    public async Task<UserCollection> FindByName(string usernames, string expansions, Fields fields)
    {
        Dictionary<string, object> pathParams = new();

        Dictionary<string, object> queryParams = new();
        queryParams.Add("usernames", usernames);
        queryParams.Add("expansions", expansions);
        queryParams.Add("fields", fields);

        List<string> queryStructNames = new();
        queryStructNames.Add('fields');

        RestRequest request = new(this.Parser.Url("/2/users/by", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<UserCollection>(response.Content);
        }

        if (response.ErrorException != null)
        {
            throw new ClientException("An unknown error occurred: " + response.ErrorException.Message, response.ErrorException);
        }

        throw (int) response.StatusCode switch
        {
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }


}
